#!/usr/bin/env python3 
import http.server
import socketserver

class MyRequestHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        if self.path == '/':
            self.path = '/gui.html' # html file you want to have show up
        return http.server.SimpleHTTPRequestHandler.do_GET(self)

Handler = MyRequestHandler
server = socketserver.TCPServer(('10.214.152.67', 9050), Handler) # IP address of machine, and Port 
# number different than webserver
server.serve_forever()
